version: "3.9"

services:
  backend:
    build:
      context: ..
      dockerfile: docker/backend.Dockerfile
    container_name: redteam-backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    restart: always
